dataset:
  base: base_dataset
  full: geo_dataset
  type: parquet
tf_idf_matrix:
  name: tf_idf_sparse_matrix
  type: npz
tf_idf_features:
  name: features
  type: parquet
data_aug_params:
  nlp_vocab: pt_core_news_lg
  nlp_language: pt
  translator_model: facebook/nllb-200-distilled-600M
  unmasker_model: neuralmind/bert-base-portuguese-cased
  src_lang: por_Latn
  tgt_lang: deu_Latn
finetuning_params:
  base_model: t5-small
  epochs: 3